= Java EE

== Part III The Web Tier

=== 6 Getting Started with Web Applications

==== 6.1 Web Applications

A web application is a dynamic extension of a web or application server.
Tipuri de aplicații web: Presentation-oriented (HTML, XHTML, XML ...) and Service-oriented.

In the Java EE platform, web components provide the dynamic extension capabilities for a web server. 
Web components can be Java servlets, web pages implemented with JavaServer Faces technology, web service endpoints, or JSP pages

A web component eventually generates a HTTPServletResponse object. The web server converts this object to an HTTP response and returns it to the client.

Web components are supported by the services of a runtime platform called a web container.

==== 6.2 Web Application Lifecycle

A web application consists of web components; static resource files, such as images and cascading style sheets (CSS); and helper classes and libraries.

The process for creating, deploying, and executing a web application can be summarized as follows:
1.
2.
...
6.

==== 6.3 A Web Module That Uses JavaServer Faces Technology: The hello1 Example
==== 6.5 Configuring Web Applications

You can pass context parameters to the context, or you can pass initialization parameters to a servlet. Context parameters are available to the entire application.

