= Self-study Exercises 
:experimental:

Repere (sau „regulile jocului”):

. Ordinea este un aspect important al acestor sarcini. Ordinea in general este un concept important, atunci cand ne intereseaza calitatea unui produs: fie acesta rezultatul invatarii sau solutia unei probleme.
In aceleasi conditii un efort poate fi mai mare daca nu alegem corect ordinea (algoritumul). 
+
[quote, The Ghost, The Ghost Writer]
____
Well, all the words are there.
They're just in the wrong order.
____
. Fiecare sarcina are componenta _Verificare_; aceasta contine instructiuni cu ajutorul carora poti sa verifci daca ai finalizat corect exercitiul.
. Orice sarcina are multe detalii (necunoscute); trebuie sa te concentrezi doar la cele importante, care te ajuta sa indeplinesti cu success instructiunile din _Verificare_; 
incearca sa nu „observi” detaliile care nu le intelegi si care nu-ti sunt de folos in verificarea exercitului (ele vor fi dezvoltate in exercitiile urmatoare).
. Sun acceptate intrebarile ce tin de formulare
+
[quote, Stephen King, The Dark Tower III: The Waste Lands]
The lessons which are remembered the longest, Roland knew, are always the ones that are self-taught.
. Sa nu-ti fie frica sa gresesti; intr-un manual de filosofie pe care l-am citit in timpul studentiei era scris ca la adevar poti ajunge si din greseala, de exemplu, te apuci sa rezolvi o problema de matematica si 
daca n-ai comis erori in timpul rezolvarii, atunci solutia la care ai ajuns e cea cautata, dar e posibil sa comiti erori in timpul rezolvarii si printr-o coincidenta (norocoasa) sa ajungi la aceeasi solutie corecta. 
Cand incerc ceva si ajungi la final fara greseli eu nu-s sigur ca ai ajuns fara erori de intelegere (ele pot fi depistate la evaluare); cand gresesc acest lucru demosntreaza ca sunt prezente erori de intelegere si 
incercand sa trec de greseala rezolv eroarea de intelegere.
. Sarcinile au forma imperativa si folosesc adresarea „Tu” in loc de „Dvs.” pentru a ne putea concentra la ceea ce e mai important nemijlocit.

== Sarcini de lucru

. Instaleaza JDK 8.
Verificare:: Din linia de comanda verifica versiunea de java
+
[source, shell]
java -version
+
se va afisa un mesaj analog cu cel ce urmeaza
+
[source, shell]
----
C:\Users\rdumbraveanu>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
----
+
Eventual ai putea sa intri in dosarul _C:\Program Files\Java_ si sa analizezi continutul acestuia, trebuie sa existe dosar care sa inceapa cu _jdk_ si sa contina cifra 8, de exemplu _jdk1.8.0_251_. 

. Instaleaza IntelliJ IDEA Community.
Sugestie:: https://www.jetbrains.com/idea/download/#section=windows

. Creeaza un proiect Maven simplu. Analizeaza ce dosare si ce fisiere contine proiectul nou generat.
Sugestie:: In IDEA selecteaza menu:File[New > Project...], apoi in fereastra _New Project_, alege _Maven_ (in coloana stanga), bifeaza _Create from archetype_ si selecteaza sablonul _org.apache.maven.archetypes:maven-archetype-webapp_.
Verificare:: 
.. menu:View[Tool Windows > Maven], in fereastra nou aparuta deschide nodul _Lifecycle_ si dublu clic pe _compile_; se va afisa un mesaj care in final van avea un fragment analog cu cel ce urmeaza
+
[source, shell]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.016 s
[INFO] Finished at: 2021-01-13T17:04:32+02:00
[INFO] ------------------------------------------------------------------------
----
.. proiectul ar trebui sa contina cel putin aceste dosare si fisere
+
[source,ascii,subs="verbatim,attributes"]
----
  |-- src
     |-- main
  `-- pom.xml
----

. Elaboreaza o aplicatie web simpla care utilizeaza Spring Boot.
Sugestie:: https://start.spring.io/, alege Java 8, iar din depentinte include _Spring Web_.
Verificare:: 
Vom verifica succesului acestei sarcini prin analogie cu Apache HTTP Server; acesta afiseaza mesajul _It works!_ la accesarea http://localhost/ daca e instalat cu succes. 
Asadar deschide proiectul generat in IDEA si in _Project_ tool window creeaza clasa `controller.HomeController` cu urmatorul continut:
+
[source,java]
----
@RestController("/")
public class HomeController {

    @GetMapping("/")
    public String home() {
        return "It works!";
    }
}
----
+
ruleaza proiectul, apoi acceseaza http://localhost:8080/ folosind navigatorul web, presupun ca intuiesti care mesaj trebui sa fie afisat?

. Creeaza clasa `Customer` cu trei atribute: `id` (tip `Integer`), `firstName` (tip `String`), `lastName` (tip `String`); pentru cele trei atribute, trebuie definite getter-e si setter-e.
Verificare:: Creeaza urmatorul controller CustomerController
+
[source, java]
----
package <calea.pana.la.clasa.curenta>

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import <calea.pana.la.clasa.Customer.inclusiv>

@RestController
public class CustomerController {

    @GetMapping("/customers")
    public Customer customer() {
        Customer customer = new Customer();  
        customer.setFirstName("Jack");
        customer.setLastName("Bauer");

        return customer;
    }
}
----
+
ruleaza proiectul, apoi acceseaza http://localhost:8080/customers folosind navigatorul web, ar trebui sa vezi reprezentarea JSON a obiectului `Customer` creat in controller.

. In fisierul _pom.xml_, in sectiunea _dependencies_ adauga dependinta:
+
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>
----
+
Creeaza in dosarul _src/main/resources/templates_ fisierul _customer.html_ cu urmatorul continut:
+
[source,html]
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Getting Started: Serving Web Content</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
    <div>
        <p>Id: <span th:text="${customer.id}">none</span>.</p>
        <p>First name: <span th:text="${customer.firstName}">none</span>.</p>
        <p>Last name: <span th:text="${customer.lastName}">none</span>.</p>
    </div>
</body>
</html>
----
+
Iar in `CustomerController` inlocuieste adnotarea `@RestController` cu `@Controller`, la metoda `customer()` adauga in lista de parametri `Model model`, schimba tipul de intoarcere din `Customer` in `String`, inauntrul metodei, 
in loc de `return customer;` vom returna valoarea `"customer"` (de fapt e numele fisierului _customer.html_ fara extensie) si in final inainte de a returna aceasta valoare vom pune variabila `customer` pe model 
in felul urmator `model.addAttribute("customer", customer)`.

Verificare:: acceseaza http://localhost:8080/customers folosind navigatorul web, ar trebui sa vezi o pagina HTML cu atributele obiectului `Customer` creat in controller.
Sugestie:: In caz ca se va afisa mesajul de eroare _This application has no explicit mapping for /error, so you are seeing this as a fallback._ deschide menu:View[Tool Windows > Maven], 
in fereastra nou aparuta deschide nodul _Dependencies_ si verifica daca in lista de dependinte e prezenta _spring-boot-starte-thymeleaf_; in caz ca lipseste click pe _Reload All Maven Projects_.

Intrebare:: In caz ca vom uita sa inlocuim adnotarea `@RestController` cu `@Controller`, atunci navigatorul va afisa doar cuvantul _customer_; de ce?

. Muta variabila locala `Customer customer` din metoda `String customer(Model)` cu un nivel mai sus, adica deja cu rol de atribut al clasei `CustomerController`, iar initializarea variabilei o vei face in constructor:
+
[source, java]
----
public class CustomerController {

    private Customer customer;

    public CustomerController() {
        customer = new Customer();
        customer.setFirstName("Jack");
        customer.setLastName("Bauer");
    }
	
	/* ... */
}
----
+
astfel in metoda `customer(Model)` vor ramane doar:
+
[source, java]
----
model.addAttribute("customer", customer);

return "customer";
----
+
Adauga metoda care va fisa formularul
+
[source, java]
----
    @GetMapping("/customers/edit")
    public String customerForm(Model model) {
        model.addAttribute("customer", customer);

        return "customer-form";
    }
----
+
si metoda care va primi datele de la formular
+
[source, java]
----
    @PostMapping("/customers")
    public String customerSubmit(@ModelAttribute Customer customer, Model model) {
        this.customer.setFirstName(customer.getFirstName());
        this.customer.setLastName(customer.getLastName());

        return "redirect:/customers";
    }
----
+
In fisierul _customer.html_ adauga
+
[source,html]
----
<a th:href="@{/customers/edit}">Edit</a>
----
+
si creeaza fisierul _customer-form.html_
+
[source, html]
----
<!DOCTYPE HTML>
<html xmlns:th="https://www.thymeleaf.org">
<head>
    <title>Getting Started: Handling Form Submission</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
	<h1>Form</h1>
    <form action="#" th:action="@{/customers}" th:object="${customer}" method="post">
    	<p>Id: <input type="text" th:field="*{id}" /></p>
        <p>First name: <input type="text" th:field="*{firstName}" /></p>
		<p>Last name: <input type="text" th:field="*{lastName}" /></p>
        <p><input type="submit" value="Submit" /> <input type="reset" value="Reset" /></p>
    </form>
</body>
</html>
----

Verificare:: acceseaza http://localhost:8081/customers, apasa pe link-ul _Edit_, modifica careva valori in formular si _Submit_; in pagina nou aparauta trebuie sa vezi noile date.

. [pagina web care afiseaza lista de customeri]

. [pagina web care valideaza un customer]

. [pagina web care creaza un customer]

. [stocarea acestora inbaza de date]

. [legatura Customer Address]

. [CRUD Address]

. [search]